.PHONY: start-testnet deploy-backend deploy update-backend update

start-testnet:
	sudo dfx start --clean

deploy-backend:
	sudo dfx deploy ICPoaps_backend

deploy:
	sudo dfx deploy

update-backend:
	sudo dfx deploy ICPoaps_backend

update:
	sudo dfx deploy
